plugins {
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
}

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly project(':panillax-api')
    paperweight.paperDevBundle("26.2.build.+")
    implementation 'net.kyori:adventure-text-serializer-ansi:5.1.1'
    implementation 'de.tr7zw:item-nbt-api:2.15.7'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}