name: PanillaX
version: ${version}
main: com.ruinscraft.panilla.bukkit.PanillaPlugin
api-version: 26.2
folia-supported: true
authors: [ ds58, Tig3r98 ]
description: Prevent abusive NBT and harmful packets
website: https://github.com/Tig3r98/Panilla
permissions:
  panilla.log.chat:
    description: View warning logs in chat if enabled in the config
    default: op
  panilla.command.reload:
    description: Reload the Panilla config
    default: op
  panilla.command.debug:
    description: View debug information
    default: op
  panilla.bypass:
    description: Bypass packet checks
    default: op